### ISSUE TITLE
TDD in Python with pytest (simple calculator questions)

### ISSUE THREAD

**Issue by labdmitriy** [TheDigitalCatOnline/blog_source#11]
Hi Leonardo, 

Thanks a lot for your blog series!

Could you please provide some information about simple calculator's requirements and its testing using TDD:
- As I understand this example of calculator is for integer input values (based on examples which you use), but [requirements](https://www.thedigitalcatonline.com/blog/2020/09/10/tdd-in-python-with-pytest-part-1/#requirements) for calculator in Part 1 do not tell anything about integer input values. Do I understand correctly that this example is also for float input values? If so, how do you think, do we need, according to TDD, have the tests based on float input values as more generic version of the tests, or we need tests for both integer and float types?
- If we use, for example, integer values for division or float values for all operations, we also face the problem of float type representation error - do we need to consider it somehow in tests?
**Update**: I found in step 9 that pytest.approx() can be used to deal with float representation errors.

Thank you.

**Comment by lgiordani** [comment]
Dmitry, thanks a lot for all the questions and the error corrections you sent. Rest assured I will tackle them as soon as possible. As for your questions:
1. That's an interesting point that I haven't considered. I think we actually should check that everything works with float, but it's not a mistake (in my opinion) to consider float as a superset of integer and just get away with that. In practice, since this is a beginner's guide, I think it might be better to add later a couple of tests that check floats and to reason that these can supersede the integer ones. I will think about it, thanks for the input!
2. Yes, I think `pytest.approx()` is the best way to deal with that problem. Clearly, if one is testing a scientific application requirements might be more stringent, but overall the representation is always an approximation.

I will try to update the series keeping in mind these questions. I'll leave this open as a reminder until I have something written to discuss. Thanks!

**Comment by labdmitriy** [comment]
Hi Leonardo, 

Thank you for your answer!

**Comment by lgiordani** [comment]
@labdmitriy I addressed type-checking in this new section of the second post https://www.thedigitalcatonline.com/blog/2020/09/11/tdd-in-python-with-pytest-part-2/#the-problem-of-types. Please let me know it it makes sense or if there are still open questions. It's always useful to discuss such topics!
