### ISSUE TITLE
Typo in the link

### ISSUE THREAD

**Issue by borislavmavrin** [TheDigitalCatOnline/blog_source#26]
`git clone https://github.com/YOURUSERNAME/simple_calculator` 

should be 

`git clone https://github.com/lgiordani/simple_calculator`

**Comment by lgiordani** [comment]
Borislav,

thanks for opening the issue. As you can see in the text of the post `I recommend you fork the repository on GitHub so that you are able to commit your changes`, which is why you see `YOURUSERNAME` instead of mine.

You are free to use my repository directly, but that means you won't be able to push changes remotely.

Thanks for reading my posts!

Leo
